export const CATEGORIES = [
  'Frontend',
  'Backend',
  'Full Stack',
  'Languages',
  'DSA',
  'System Design',
  'DevOps',
  'Cloud',
  'Git & Tools',
  'ML / AI',
  'Mobile',
  'Databases',
  'CS Fundamentals',
];

// TODO go through these and check for dead links once in a while
export const RESOURCES = [
  {
    title: 'The Odin Project — Foundations',
    url: 'https://www.theodinproject.com/paths/foundations/courses/foundations',
    type: 'course',
    category: 'Frontend',
    platform: 'The Odin Project',
    description: 'Full open-source curriculum covering HTML, CSS, JavaScript, Git, and command line from zero.',
    tags: ['html', 'css', 'javascript', 'beginner'],
  },
  {
    title: 'MDN Web Docs',
    url: 'https://developer.mozilla.org/en-US/docs/Learn',
    type: 'docs',
    category: 'Frontend',
    platform: 'Mozilla',
    tags: ['html', 'css', 'javascript'],
  },
  {
    title: 'React Official Tutorial',
    url: 'https://react.dev/learn',
    type: 'docs',
    category: 'Frontend',
    platform: 'React',
    description: 'The rewritten react.dev docs teach React from fundamentals with interactive sandboxes.',
    tags: ['react', 'hooks', 'components'],
  },
  {
    title: 'JavaScript.info',
    url: 'https://javascript.info/',
    type: 'docs',
    category: 'Frontend',
    platform: 'javascript.info',
    description: 'Modern JavaScript tutorial, from basics to advanced topics, updated and extremely thorough.',
    tags: ['javascript', 'es6', 'async'],
  },
  {
    title: 'CSS Tricks Almanac',
    url: 'https://css-tricks.com/almanac/',
    type: 'article',
    category: 'Frontend',
    platform: 'CSS Tricks',
    description: 'Complete reference of CSS properties and selectors with examples and gotchas.',
    tags: ['css', 'flexbox', 'grid'],
  },
  {
    title: 'web.dev Learn',
    url: 'https://web.dev/learn/',
    type: 'course',
    category: 'Frontend',
    platform: 'Google',
    description: "Google's free structured courses on HTML, CSS, accessibility, performance, and PWAs.",
    tags: ['html', 'css', 'performance', 'accessibility'],
  },

  {
    title: 'Node.js Official Learn',
    url: 'https://nodejs.org/en/learn',
    type: 'docs',
    category: 'Backend',
    platform: 'Node.js',
    description: 'Official guides covering async, streams, file system, modules, debugging.',
    tags: ['node', 'javascript'],
  },
  {
    title: 'Express.js Guide',
    url: 'https://expressjs.com/en/guide/routing.html',
    type: 'docs',
    category: 'Backend',
    platform: 'Express',
    description: 'Official Express docs: routing, middleware, error handling, production best practices.',
    tags: ['express', 'node', 'rest'],
  },
  {
    title: 'Python Official Tutorial',
    url: 'https://docs.python.org/3/tutorial/',
    type: 'docs',
    category: 'Backend',
    platform: 'Python',
    description: "Python's own tutorial — the best starting point for the language.",
    tags: ['python'],
  },
  {
    title: 'Django Girls Tutorial',
    url: 'https://tutorial.djangogirls.org/',
    type: 'course',
    category: 'Backend',
    platform: 'Django Girls',
    description: 'Build your first Django web app. Free, beginner-friendly, step-by-step.',
    tags: ['django', 'python', 'beginner'],
  },
  {
    title: 'Go By Example',
    url: 'https://gobyexample.com/',
    type: 'article',
    category: 'Backend',
    platform: 'Go',
    description: 'Hands-on Go tutorial, one concept per page with runnable code.',
    tags: ['go', 'golang'],
  },

  {
    title: 'Full Stack Open',
    url: 'https://fullstackopen.com/en/',
    type: 'course',
    category: 'Full Stack',
    platform: 'University of Helsinki',
    description: 'MERN + GraphQL + TypeScript + testing + CI/CD. Free, open, rigorous. Certification available.',
    tags: ['react', 'node', 'mongodb', 'graphql'],
  },
  {
    title: 'freeCodeCamp — Responsive Web Design',
    url: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    type: 'course',
    category: 'Full Stack',
    platform: 'freeCodeCamp',
    description: '300+ hours of structured learning with a free certification. Hands-on projects throughout.',
    tags: ['html', 'css', 'responsive', 'beginner'],
  },
  {
    title: 'roadmap.sh — Full Stack Developer',
    url: 'https://roadmap.sh/full-stack',
    type: 'article',
    category: 'Full Stack',
    platform: 'roadmap.sh',
    description: 'Community-maintained visual roadmap of what to learn as a full-stack engineer.',
    tags: ['roadmap', 'full-stack'],
  },

  {
    title: 'NeetCode 150',
    url: 'https://neetcode.io/practice',
    type: 'course',
    category: 'DSA',
    platform: 'NeetCode',
    description: '150 essential LeetCode problems categorized by pattern, with free video solutions.',
    tags: ['leetcode', 'interview', 'algorithms'],
  },
  {
    title: 'CS50 Lecture 3 — Algorithms',
    url: 'https://cs50.harvard.edu/x/2024/weeks/3/',
    type: 'video',
    category: 'DSA',
    platform: 'Harvard CS50',
    description: "Harvard's CS50 covers searching, sorting, and recursion clearly and visually.",
    tags: ['algorithms', 'recursion', 'sort'],
  },
  {
    title: 'Visualgo',
    url: 'https://visualgo.net/en',
    type: 'article',
    category: 'DSA',
    platform: 'Visualgo',
    description: 'Interactive visualizations of data structures and algorithms — sorting, trees, graphs, etc.',
    tags: ['visualization', 'algorithms', 'data structures'],
  },
  {
    title: 'The Algorithms — Open Source',
    url: 'https://the-algorithms.com/',
    type: 'article',
    category: 'DSA',
    platform: 'The Algorithms',
    description: 'Open-source implementations of every classic algorithm in many languages, fully free.',
    tags: ['algorithms', 'open source'],
  },

  {
    title: 'System Design Primer',
    url: 'https://github.com/donnemartin/system-design-primer',
    type: 'article',
    category: 'System Design',
    platform: 'GitHub',
    description: '260k+ star repo covering system design basics, case studies, and interview prep.',
    tags: ['system design', 'interview', 'scalability'],
  },
  {
    title: 'Hussein Nasser — System Design',
    url: 'https://www.youtube.com/@hnasr',
    type: 'video',
    category: 'System Design',
    platform: 'YouTube',
    description: 'Deep dives into databases, networking, backend engineering from a senior engineer.',
    tags: ['databases', 'networking', 'backend'],
  },
  {
    title: 'ByteByteGo YouTube',
    url: 'https://www.youtube.com/@ByteByteGo',
    type: 'video',
    category: 'System Design',
    platform: 'YouTube',
    description: 'Short visual explanations of system design concepts and real architectures.',
    tags: ['system design', 'architecture'],
  },

  {
    title: 'roadmap.sh — DevOps',
    url: 'https://roadmap.sh/devops',
    type: 'article',
    category: 'DevOps',
    platform: 'roadmap.sh',
    description: 'Visual roadmap of DevOps skills: Linux, CI/CD, Docker, Kubernetes, observability.',
    tags: ['devops', 'roadmap'],
  },
  {
    title: 'Docker Get Started',
    url: 'https://docs.docker.com/get-started/',
    type: 'docs',
    category: 'DevOps',
    platform: 'Docker',
    description: 'Official Docker onboarding: containers, images, Compose, networking, volumes.',
    tags: ['docker', 'containers'],
  },
  {
    title: 'Kubernetes Basics',
    url: 'https://kubernetes.io/docs/tutorials/kubernetes-basics/',
    type: 'docs',
    category: 'DevOps',
    platform: 'Kubernetes',
    description: 'Hands-on tutorial to create and manage clusters, pods, and services.',
    tags: ['kubernetes', 'k8s'],
  },
  {
    title: 'TechWorld with Nana — DevOps Crash Course',
    url: 'https://www.youtube.com/@TechWorldwithNana',
    type: 'video',
    category: 'DevOps',
    platform: 'YouTube',
    description: 'Free full DevOps bootcamp: Linux, Docker, K8s, Jenkins, Terraform, AWS.',
    tags: ['devops', 'kubernetes', 'docker', 'aws'],
  },

  {
    title: 'Fast.ai — Practical Deep Learning',
    url: 'https://course.fast.ai/',
    type: 'course',
    category: 'ML / AI',
    platform: 'Fast.ai',
    description: 'Top-down deep learning course that gets you training models in lesson 1. Free.',
    tags: ['deep learning', 'pytorch', 'practical'],
  },
  {
    title: 'Andrej Karpathy — Zero to Hero',
    url: 'https://karpathy.ai/zero-to-hero.html',
    type: 'video',
    category: 'ML / AI',
    platform: 'YouTube',
    description: 'Build a neural network and a GPT from scratch, line by line, with one of the best teachers in ML.',
    tags: ['neural networks', 'gpt', 'llm', 'pytorch'],
  },
  {
    title: 'Hugging Face Course',
    url: 'https://huggingface.co/learn/nlp-course',
    type: 'course',
    category: 'ML / AI',
    platform: 'Hugging Face',
    description: 'Free NLP course using Transformers, Datasets, and Hub. Hands-on.',
    tags: ['nlp', 'transformers', 'huggingface'],
  },
  {
    title: '3Blue1Brown — Neural Networks',
    url: 'https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi',
    type: 'video',
    category: 'ML / AI',
    platform: 'YouTube',
    description: 'Visual intuition for how neural nets work — best starting point for the math.',
    tags: ['neural networks', 'visualization'],
  },

  {
    title: 'React Native Docs',
    url: 'https://reactnative.dev/docs/getting-started',
    type: 'docs',
    category: 'Mobile',
    platform: 'React Native',
    description: 'Official guide for building native iOS and Android apps with React.',
    tags: ['react native', 'mobile', 'ios', 'android'],
  },
  {
    title: 'Flutter Codelabs',
    url: 'https://docs.flutter.dev/codelabs',
    type: 'course',
    category: 'Mobile',
    platform: 'Flutter',
    description: 'Hands-on Flutter tutorials from Google covering UI, state, APIs, and layout.',
    tags: ['flutter', 'dart', 'mobile'],
  },

  {
    title: 'Use The Index, Luke!',
    url: 'https://use-the-index-luke.com/',
    type: 'article',
    category: 'Databases',
    platform: 'Use The Index Luke',
    description: 'The free, definitive guide to SQL indexing and performance. Essential for backend engineers.',
    tags: ['sql', 'indexing', 'performance'],
  },
  {
    title: 'PostgreSQL Tutorial',
    url: 'https://www.postgresqltutorial.com/',
    type: 'docs',
    category: 'Databases',
    platform: 'PostgreSQL Tutorial',
    description: 'Free comprehensive PostgreSQL tutorial from zero to advanced.',
    tags: ['postgres', 'sql'],
  },
  {
    title: 'MongoDB University',
    url: 'https://learn.mongodb.com/',
    type: 'course',
    category: 'Databases',
    platform: 'MongoDB',
    description: 'Free official MongoDB courses with certifications: developer, DBA, data modeling.',
    tags: ['mongodb', 'nosql'],
  },
  {
    title: 'SQLBolt',
    url: 'https://sqlbolt.com/',
    type: 'course',
    category: 'Databases',
    platform: 'SQLBolt',
    description: 'Interactive SQL lessons and exercises, zero setup required. Perfect for beginners.',
    tags: ['sql', 'beginner'],
  },

  {
    title: 'Harvard CS50',
    url: 'https://cs50.harvard.edu/x/',
    type: 'course',
    category: 'CS Fundamentals',
    platform: 'Harvard',
    description: "Harvard's legendary intro to CS. Free, rigorous, covers C, Python, SQL, web, AI.",
    tags: ['cs', 'beginner', 'python', 'c'],
  },
  {
    title: 'MIT 6.006 — Intro to Algorithms',
    url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    type: 'course',
    category: 'CS Fundamentals',
    platform: 'MIT OCW',
    description: 'MIT OpenCourseWare intro to algorithms — lectures, problem sets, exams, all free.',
    tags: ['algorithms', 'mit'],
  },
  {
    title: 'Missing Semester of Your CS Education',
    url: 'https://missing.csail.mit.edu/',
    type: 'course',
    category: 'CS Fundamentals',
    platform: 'MIT',
    description: 'The tools schools never teach: shell, git, vim, ssh, debugging, build systems, security.',
    tags: ['git', 'shell', 'tooling'],
  },
  {
    title: 'Teach Yourself CS',
    url: 'https://teachyourselfcs.com/',
    type: 'article',
    category: 'CS Fundamentals',
    platform: 'Teach Yourself CS',
    description: 'A curated self-study guide for all of CS fundamentals: picks the best book + course per topic.',
    tags: ['cs', 'self-study'],
  },

  {
    title: 'MDN — JavaScript Guide',
    url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide',
    type: 'docs',
    category: 'Frontend',
    platform: 'MDN',
    description: 'Complete JavaScript language guide: grammar, types, control flow, functions, classes, iterators, modules.',
    tags: ['javascript', 'reference'],
  },
  {
    title: 'MDN — HTML Element Reference',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTML/Element',
    type: 'docs',
    category: 'Frontend',
    platform: 'MDN',
    description: 'Every HTML element with attributes, examples, and accessibility notes.',
    tags: ['html', 'reference'],
  },
  {
    title: 'MDN — CSS Reference',
    url: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Reference',
    type: 'docs',
    category: 'Frontend',
    platform: 'MDN',
    description: 'Every CSS property and selector with browser support and examples.',
    tags: ['css', 'reference'],
  },
  {
    title: 'MDN — Web APIs',
    url: 'https://developer.mozilla.org/en-US/docs/Web/API',
    type: 'docs',
    category: 'Frontend',
    platform: 'MDN',
    description: 'All browser Web APIs: DOM, Fetch, WebSockets, Workers, Storage, Canvas, WebRTC, and more.',
    tags: ['web api', 'dom'],
  },
  {
    title: 'MDN — Accessibility (a11y)',
    url: 'https://developer.mozilla.org/en-US/docs/Web/Accessibility',
    type: 'docs',
    category: 'Frontend',
    platform: 'MDN',
    description: 'Comprehensive accessibility guide: ARIA, keyboard, screen readers, WCAG conformance.',
    tags: ['accessibility', 'aria', 'a11y'],
  },

  {
    title: 'Kevin Powell — CSS',
    url: 'https://www.youtube.com/@KevinPowell',
    type: 'video',
    category: 'Frontend',
    platform: 'YouTube',
    description: 'The definitive free YouTube channel for CSS — Flexbox, Grid, animations, modern selectors.',
    tags: ['css', 'flexbox', 'grid'],
  },
  {
    title: 'Web Dev Simplified',
    url: 'https://www.youtube.com/@WebDevSimplified',
    type: 'video',
    category: 'Frontend',
    platform: 'YouTube',
    description: 'Kyle Cook explains JS, React, and CSS concepts in 10-minute focused tutorials.',
    tags: ['javascript', 'react', 'css'],
  },
  {
    title: 'The Net Ninja',
    url: 'https://www.youtube.com/@NetNinja',
    type: 'video',
    category: 'Full Stack',
    platform: 'YouTube',
    description: 'Hundreds of free tutorial playlists: React, Vue, Node, Firebase, MongoDB, TypeScript, Next.js, more.',
    tags: ['react', 'node', 'vue', 'next'],
  },
  {
    title: 'Traversy Media',
    url: 'https://www.youtube.com/@TraversyMedia',
    type: 'video',
    category: 'Full Stack',
    platform: 'YouTube',
    description: 'Brad Traversy: full-stack crash courses, project builds, and frameworks. One of the largest free dev channels.',
    tags: ['full-stack', 'crash course'],
  },
  {
    title: 'freeCodeCamp YouTube',
    url: 'https://www.youtube.com/@freecodecamp',
    type: 'video',
    category: 'Full Stack',
    platform: 'YouTube',
    description: 'Free 5-15 hour full courses on JavaScript, Python, React, ML, SQL, Rust, Go, and more.',
    tags: ['full-stack', 'long course'],
  },
  {
    title: 'Jack Herrington — React',
    url: 'https://www.youtube.com/@jherr',
    type: 'video',
    category: 'Frontend',
    platform: 'YouTube',
    description: 'Senior React content: hooks, server components, Next.js, monorepos, performance, patterns.',
    tags: ['react', 'next', 'advanced'],
  },
  {
    title: 'Theo (t3.gg)',
    url: 'https://www.youtube.com/@t3dotgg',
    type: 'video',
    category: 'Full Stack',
    platform: 'YouTube',
    description: 'Modern TypeScript full-stack: Next.js, tRPC, Prisma, Tailwind, and the T3 stack.',
    tags: ['typescript', 'next', 'trpc'],
  },
  {
    title: 'Fireship',
    url: 'https://www.youtube.com/@Fireship',
    type: 'video',
    category: 'Full Stack',
    platform: 'YouTube',
    description: 'Fast-paced 100-second tech explainers and concise full project builds across the modern web stack.',
    tags: ['full-stack', 'overview'],
  },
  {
    title: 'Programming with Mosh',
    url: 'https://www.youtube.com/@programmingwithmosh',
    type: 'video',
    category: 'Languages',
    platform: 'YouTube',
    description: 'Free intro full courses in Python, JavaScript, TypeScript, C#, SQL, and React.',
    tags: ['python', 'javascript', 'beginner'],
  },
  {
    title: 'Corey Schafer — Python',
    url: 'https://www.youtube.com/@coreyms',
    type: 'video',
    category: 'Languages',
    platform: 'YouTube',
    description: 'Best-in-class Python tutorials: language fundamentals, OOP, decorators, Django, Flask, pandas.',
    tags: ['python', 'django', 'flask'],
  },
  {
    title: 'Sentdex',
    url: 'https://www.youtube.com/@sentdex',
    type: 'video',
    category: 'ML / AI',
    platform: 'YouTube',
    description: 'Practical Python ML tutorials: scikit-learn, TensorFlow, PyTorch, NLP, reinforcement learning.',
    tags: ['python', 'machine learning'],
  },
  {
    title: 'StatQuest with Josh Starmer',
    url: 'https://www.youtube.com/@statquest',
    type: 'video',
    category: 'ML / AI',
    platform: 'YouTube',
    description: 'Statistics and machine learning explained clearly with simple visuals. BAM!',
    tags: ['statistics', 'ml', 'visualization'],
  },
  {
    title: 'Two Minute Papers',
    url: 'https://www.youtube.com/@TwoMinutePapers',
    type: 'video',
    category: 'ML / AI',
    platform: 'YouTube',
    description: 'Stay current on AI research: paper summaries with visualizations, accessible to everyone.',
    tags: ['research', 'ai', 'papers'],
  },

  {
    title: 'Striver — takeUforward',
    url: 'https://www.youtube.com/@takeUforward',
    type: 'video',
    category: 'DSA',
    platform: 'YouTube',
    description: 'Striver\'s SDE Sheet, A2Z DSA Sheet, and complete data structures and algorithms tutorials in C++/Java.',
    tags: ['dsa', 'leetcode', 'interview'],
  },
  {
    title: 'Abdul Bari — Algorithms',
    url: 'https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O',
    type: 'video',
    category: 'DSA',
    platform: 'YouTube',
    description: 'the classic algorithms playlist. long but worth it.',
    tags: ['algorithms'],
  },
  {
    title: 'William Fiset — Graph Theory',
    url: 'https://www.youtube.com/playlist?list=PLDV1Zeh2NRsDGO4--qE8yH72HFL1Km93P',
    type: 'video',
    category: 'DSA',
    platform: 'YouTube',
    description: 'Comprehensive free graph theory + algorithms course. Used by Google engineers as a reference.',
    tags: ['graphs', 'algorithms'],
  },
  {
    title: 'Apna College — DSA',
    url: 'https://www.youtube.com/@ApnaCollegeOfficial',
    type: 'video',
    category: 'DSA',
    platform: 'YouTube',
    description: 'Free Hindi-friendly DSA, C++, Java, and full-stack courses very popular among Indian students.',
    tags: ['dsa', 'cpp', 'java', 'hindi'],
  },

  {
    title: 'Gaurav Sen — System Design',
    url: 'https://www.youtube.com/@gkcs',
    type: 'video',
    category: 'System Design',
    platform: 'YouTube',
    description: 'Classic free system design videos: scalability, sharding, consistent hashing, load balancing, design problems.',
    tags: ['system design', 'interview'],
  },
  {
    title: 'Tech Dummies — Narendra L',
    url: 'https://www.youtube.com/@TechDummiesNarendraL',
    type: 'video',
    category: 'System Design',
    platform: 'YouTube',
    description: 'In-depth real-world architecture breakdowns: Uber, WhatsApp, Netflix, Twitter, and more.',
    tags: ['system design', 'architecture'],
  },

  {
    title: 'TypeScript Handbook',
    url: 'https://www.typescriptlang.org/docs/handbook/intro.html',
    type: 'docs',
    category: 'Languages',
    platform: 'TypeScript',
    description: 'Official TypeScript documentation: types, interfaces, generics, narrowing, modules.',
    tags: ['typescript'],
  },
  {
    title: 'Rust Book',
    url: 'https://doc.rust-lang.org/book/',
    type: 'docs',
    category: 'Languages',
    platform: 'Rust',
    description: '"The Book" — the official, comprehensive, free guide to Rust. Best starting point for the language.',
    tags: ['rust'],
  },
  {
    title: 'Rustlings',
    url: 'https://github.com/rust-lang/rustlings',
    type: 'course',
    category: 'Languages',
    platform: 'GitHub',
    description: 'Small exercises to get you used to reading and writing Rust code, paired with the Rust Book.',
    tags: ['rust', 'exercises'],
  },
  {
    title: 'Java — dev.java',
    url: 'https://dev.java/learn/',
    type: 'docs',
    category: 'Languages',
    platform: 'Oracle',
    description: 'Official Oracle Java tutorials covering language basics, modern features, and standard library.',
    tags: ['java'],
  },
  {
    title: 'cppreference',
    url: 'https://en.cppreference.com/w/',
    type: 'docs',
    category: 'Languages',
    platform: 'cppreference',
    description: 'The most accurate and comprehensive C and C++ reference. Used by every C++ engineer.',
    tags: ['cpp', 'c'],
  },
  {
    title: 'learncpp.com',
    url: 'https://www.learncpp.com/',
    type: 'course',
    category: 'Languages',
    platform: 'learncpp',
    description: 'Free, structured, beginner-to-advanced C++ tutorial. The recommended free C++ learning path.',
    tags: ['cpp', 'beginner'],
  },
  {
    title: 'A Tour of Go',
    url: 'https://go.dev/tour/',
    type: 'course',
    category: 'Languages',
    platform: 'Go',
    description: "Official interactive Go tour right in the browser. Learn Go's syntax in an hour.",
    tags: ['go', 'golang'],
  },
  {
    title: 'Kotlin Docs',
    url: 'https://kotlinlang.org/docs/home.html',
    type: 'docs',
    category: 'Languages',
    platform: 'JetBrains',
    description: 'Official Kotlin documentation — language basics, Android, multiplatform, coroutines.',
    tags: ['kotlin', 'jvm'],
  },

  {
    title: 'Next.js Docs',
    url: 'https://nextjs.org/docs',
    type: 'docs',
    category: 'Frontend',
    platform: 'Next.js',
    description: 'Official Next.js docs: app router, server components, routing, data fetching, deployment.',
    tags: ['next', 'react', 'ssr'],
  },
  {
    title: 'Vue.js Guide',
    url: 'https://vuejs.org/guide/introduction.html',
    type: 'docs',
    category: 'Frontend',
    platform: 'Vue',
    description: 'Official Vue 3 guide: reactivity, components, composition API, Vue Router, Pinia.',
    tags: ['vue'],
  },
  {
    title: 'Svelte Tutorial',
    url: 'https://learn.svelte.dev/',
    type: 'course',
    category: 'Frontend',
    platform: 'Svelte',
    description: 'Interactive in-browser tutorial covering Svelte and SvelteKit step by step.',
    tags: ['svelte', 'sveltekit'],
  },
  {
    title: 'Tailwind CSS Docs',
    url: 'https://tailwindcss.com/docs',
    type: 'docs',
    category: 'Frontend',
    platform: 'Tailwind',
    description: 'Official Tailwind CSS documentation with searchable utility reference and dark mode, responsive, and config guides.',
    tags: ['tailwind', 'css'],
  },
  {
    title: 'TanStack Query Docs',
    url: 'https://tanstack.com/query/latest/docs/framework/react/overview',
    type: 'docs',
    category: 'Frontend',
    platform: 'TanStack',
    description: 'Official docs for React Query — data fetching, caching, sync, server state for React.',
    tags: ['react query', 'data fetching'],
  },

  {
    title: 'AWS Skill Builder (Free)',
    url: 'https://skillbuilder.aws/',
    type: 'course',
    category: 'Cloud',
    platform: 'AWS',
    description: "Amazon's free training portal: hundreds of free AWS courses, including Cloud Practitioner foundations.",
    tags: ['aws', 'cloud'],
  },
  {
    title: 'Google Cloud Skills Boost (Free)',
    url: 'https://www.cloudskillsboost.google/',
    type: 'course',
    category: 'Cloud',
    platform: 'Google Cloud',
    description: 'Google Cloud free learning paths and labs. Many courses and quests are completely free.',
    tags: ['gcp', 'cloud'],
  },
  {
    title: 'Microsoft Learn — Azure',
    url: 'https://learn.microsoft.com/en-us/training/azure/',
    type: 'course',
    category: 'Cloud',
    platform: 'Microsoft',
    description: 'Microsoft\'s free training platform with structured Azure learning paths and certifications prep.',
    tags: ['azure', 'cloud'],
  },
  {
    title: 'Cloudflare Learning Center',
    url: 'https://www.cloudflare.com/learning/',
    type: 'article',
    category: 'Cloud',
    platform: 'Cloudflare',
    description: 'Free deep-dive articles on networking, DNS, CDNs, security, and how the internet works.',
    tags: ['networking', 'dns', 'cdn'],
  },

  {
    title: 'Pro Git Book',
    url: 'https://git-scm.com/book/en/v2',
    type: 'docs',
    category: 'Git & Tools',
    platform: 'git-scm',
    description: 'The definitive, free, official Git book — beginner to advanced, with diagrams.',
    tags: ['git'],
  },
  {
    title: 'Learn Git Branching',
    url: 'https://learngitbranching.js.org/',
    type: 'course',
    category: 'Git & Tools',
    platform: 'Learn Git Branching',
    description: 'Visual interactive Git tutorial that teaches branching, merging, rebasing, and remotes.',
    tags: ['git', 'visual'],
  },
  {
    title: 'Atlassian Git Tutorials',
    url: 'https://www.atlassian.com/git/tutorials',
    type: 'article',
    category: 'Git & Tools',
    platform: 'Atlassian',
    description: 'Free Git tutorials covering basics, branching strategies, workflows, and advanced topics.',
    tags: ['git', 'workflow'],
  },
  {
    title: 'Linux Journey (LabEx)',
    url: 'https://labex.io/linuxjourney',
    type: 'course',
    category: 'Git & Tools',
    platform: 'LabEx',
    description: 'Free interactive Linux course covering shell, files, processes, networking, and admin.',
    tags: ['linux', 'shell'],
  },
  {
    title: 'OverAPI — Cheat Sheets',
    url: 'https://overapi.com/',
    type: 'article',
    category: 'Git & Tools',
    platform: 'OverAPI',
    description: 'Hundreds of free cheat sheets for languages, frameworks, and tools all in one place.',
    tags: ['cheat sheet', 'reference'],
  },

  {
    title: 'FastAPI Docs',
    url: 'https://fastapi.tiangolo.com/',
    type: 'docs',
    category: 'Backend',
    platform: 'FastAPI',
    description: 'Modern Python web framework. Famous for the best official tutorial in the Python ecosystem.',
    tags: ['python', 'fastapi', 'rest'],
  },
  {
    title: 'Spring Boot Guides',
    url: 'https://spring.io/guides',
    type: 'docs',
    category: 'Backend',
    platform: 'Spring',
    description: '15-minute focused getting-started guides for every Spring Boot feature.',
    tags: ['java', 'spring'],
  },
  {
    title: 'Real Python',
    url: 'https://realpython.com/',
    type: 'article',
    category: 'Backend',
    platform: 'Real Python',
    description: 'Largest collection of free Python tutorials covering web, data, automation, packaging.',
    tags: ['python'],
  },
];
